// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLights() {
  return window['go']['hue']['Hue']['GetLights']();
}

export function Startup(arg1) {
  return window['go']['hue']['Hue']['Startup'](arg1);
}

export function ToggleLight(arg1) {
  return window['go']['hue']['Hue']['ToggleLight'](arg1);
}
