// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetLights():Promise<Array<models.Light>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleGroup(arg1:models.Group):Promise<void>;

export function ToggleLight(arg1:models.Light,arg2:boolean):Promise<void>;

export function ToggleRoom(arg1:models.Room):Promise<void>;
