// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateGroup(arg1:models.Group):Promise<void>;

export function CreateGroupWithName(arg1:string):Promise<void>;

export function CreateLight(arg1:models.Light):Promise<void>;

export function CreateRoom(arg1:models.Room):Promise<void>;

export function CreateRoomWithName(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteLight(arg1:string):Promise<void>;

export function DeleteRoom(arg1:string):Promise<void>;

export function GetGroup(arg1:string):Promise<models.Group>;

export function GetGroupByName(arg1:string):Promise<models.Group>;

export function GetGroupOptions():Promise<Array<models.GroupOptions>>;

export function GetGroups():Promise<Array<models.Group>>;

export function GetLight(arg1:string):Promise<models.Light>;

export function GetLights():Promise<Array<models.Light>>;

export function GetOrCreateLight(arg1:models.Light):Promise<models.Light>;

export function GetRoom(arg1:string):Promise<models.Room>;

export function GetRoomByName(arg1:string):Promise<models.Room>;

export function GetRoomOptions():Promise<Array<models.RoomOptions>>;

export function GetRooms():Promise<Array<models.Room>>;

export function ToggleGroupLike(arg1:models.Group):Promise<void>;

export function ToggleLightLike(arg1:models.Light):Promise<void>;

export function UpdateGroup(arg1:models.Group):Promise<void>;

export function UpdateLight(arg1:models.Light,arg2:string,arg3:string):Promise<void>;

export function UpdateRoom(arg1:models.Room):Promise<void>;
