// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1) {
  return window['go']['dao']['App']['CreateGroup'](arg1);
}

export function CreateGroupWithName(arg1) {
  return window['go']['dao']['App']['CreateGroupWithName'](arg1);
}

export function CreateLight(arg1) {
  return window['go']['dao']['App']['CreateLight'](arg1);
}

export function CreateRoom(arg1) {
  return window['go']['dao']['App']['CreateRoom'](arg1);
}

export function CreateRoomWithName(arg1) {
  return window['go']['dao']['App']['CreateRoomWithName'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['dao']['App']['DeleteGroup'](arg1);
}

export function DeleteLight(arg1) {
  return window['go']['dao']['App']['DeleteLight'](arg1);
}

export function DeleteRoom(arg1) {
  return window['go']['dao']['App']['DeleteRoom'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['dao']['App']['GetGroup'](arg1);
}

export function GetGroupByName(arg1) {
  return window['go']['dao']['App']['GetGroupByName'](arg1);
}

export function GetGroupOptions() {
  return window['go']['dao']['App']['GetGroupOptions']();
}

export function GetGroups() {
  return window['go']['dao']['App']['GetGroups']();
}

export function GetLight(arg1) {
  return window['go']['dao']['App']['GetLight'](arg1);
}

export function GetLights() {
  return window['go']['dao']['App']['GetLights']();
}

export function GetOrCreateLight(arg1) {
  return window['go']['dao']['App']['GetOrCreateLight'](arg1);
}

export function GetRoom(arg1) {
  return window['go']['dao']['App']['GetRoom'](arg1);
}

export function GetRoomByName(arg1) {
  return window['go']['dao']['App']['GetRoomByName'](arg1);
}

export function GetRoomOptions() {
  return window['go']['dao']['App']['GetRoomOptions']();
}

export function GetRooms() {
  return window['go']['dao']['App']['GetRooms']();
}

export function ToggleGroupLike(arg1) {
  return window['go']['dao']['App']['ToggleGroupLike'](arg1);
}

export function ToggleLightLike(arg1) {
  return window['go']['dao']['App']['ToggleLightLike'](arg1);
}

export function ToggleRoomLike(arg1) {
  return window['go']['dao']['App']['ToggleRoomLike'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['dao']['App']['UpdateGroup'](arg1);
}

export function UpdateLight(arg1, arg2, arg3) {
  return window['go']['dao']['App']['UpdateLight'](arg1, arg2, arg3);
}

export function UpdateRoom(arg1) {
  return window['go']['dao']['App']['UpdateRoom'](arg1);
}
